language: ruby
rvm:
  - 2.2.2
before_install:
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-get -y install sqlite3=3.7.15.1-1~travis1
script:
  "bundle exec rspec"
